-- Create categories table for managing item categories
CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    color TEXT DEFAULT '#007aff',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on categories table
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations for anonymous users
CREATE POLICY "Allow all operations on categories" ON categories
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Create index for faster lookups by name
CREATE INDEX IF NOT EXISTS idx_categories_name ON categories(name);

-- Insert default categories (colors will be auto-generated by the application)
INSERT INTO categories (name, description)
SELECT * FROM (VALUES
    ('Audio zařízení', NULL),
    ('Elektroinstalační materiál', NULL),
    ('HVAC senzory', NULL),
    ('Měřicí technika', NULL),
    ('Napájecí zdroje', NULL),
    ('Ostatní', NULL),
    ('PC komponenty', NULL),
    ('PC komponenty/ ostatní', NULL),
    ('PLC a automatizace', NULL),
    ('Periferní zařízení', NULL),
    ('Ruční nářadí', NULL),
    ('Senzory a detektory', NULL),
    ('Síťové komponenty', NULL),
    ('Zabezpečovací technika', NULL)
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM categories LIMIT 1);
